$(document).ready(function(){
	$(".background-container").load("common/background.html");
	$(".board-container").load("common/board.html");
	$(".ingame-ui-container").load("common/ingame_ui.html");
	$(".lobby-ui-container").load("common/lobby_ui.html");
	$(".options-overlay-container").load("common/options_overlay.html");
	$(".profile-overlay-container").load("common/profile_overlay.html");
	$(".resolution-overlay-container").load("common/res_overlay.html");
});